name = "xaostech-webfront"
compatibility_date = "2025-12-31"
main = "src/worker.ts"

[assets]
directory = "./dist"

[env.production]
name = "xaostech-webfront"
routes = [
  { pattern = "xaostech.io/*", zone_name = "xaostech.io" }
]
