name = "xaostech-webfront"
compatibility_date = "2025-12-31"
main = "dist/_worker.js/index.js"
send_metrics = false
compatibility_flags = ["nodejs_compat", "disable_nodejs_process_v2"]

[env.production]
name = "xaostech-webfront"
main = "dist/_worker.js/index.js"
routes = [
  { pattern = "xaostech.io/*", zone_name = "xaostech.io" }
]

[env.testing]
routes = [
  { pattern = "testing.local/*", zone_name = "localhost" }
]
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1