name = "xaostech-landing"
compatibility_date = "2025-12-31"

[assets]
directory = "./dist"

[env.production]
name = "xaostech-webfront"
routes = [
  { pattern = "xaostech.io/", zone_name = "xaostech.io" },
  { pattern = "xaostech.io", zone_name = "xaostech.io" }
]
